name = "My Custom Theme"
bg = "Reset"
fg = "Green"
border = "Thick"
border_color = "White"
border_focused_color = "LightCyan"
hl_bg = "DarkGray"
solid_bg = "White"
solid_fg = "Black"
info = "LightCyan"
success = "Green"
error = "Red"
warning = "Yellow"
