#:schema ../../theme.schema.json

name = "Catppuccin Macchiato"
bg = "#181926"
fg = "#cad3f5"
border = "Rounded"
border_color = "#6e738d"
border_focused_color = "#7dc4e4"
hl_bg = "#6e738d"
solid_bg = "#a6da95"
solid_fg = "#181926"
trusted = "#a6da95"
remake = "#ed8796"
