[Home]
"q" = "Quit"
"<C-z>" = "Suspend"
"d" = { "SetMode" = "DownloadClient" }
"<enter>" = "Submit"
"asdf" = ["Down", "Down", "Up"]
"?" = "WhichKey"
"k" = "Up"
"j" = "Down"
"h" = "Left"
"l" = "Right"
"K" = [4, "Up"]
"J" = [4, "Down"]
"g" = "Top"
"G" = "Bottom"
"<esc>" = "ClearNotifications"
"z" = { "NotifyInfo" = "Test info" }
"x" = { "NotifyWarning" = "Test warning" }
"c" = { "NotifyError" = "Test error" }

[DownloadClient]
"<esc>" = { "SetMode" = "Home" }
"q" = { "SetMode" = "Home" }
"d" = { "SetMode" = "Home" }
