[Home]
"q" = "Quit"
"<C-z>" = "Suspend"
"d" = { "SetMode" = "DownloadClient" }
# "<esc>" = { "SetMode" = "DownloadClient" }
# "fasdf" = { "SetMode" = "DownloadClient" }
# "ffasdf" = { "SetMode" = "DownloadClient" }
# "quit" = { "SetMode" = "DownloadClient" }
# "q12" = { "SetMode" = "DownloadClient" }

[DownloadClient]
"<esc>" = { "SetMode" = "Home" }
"q" = { "SetMode" = "Home" }
"d" = { "SetMode" = "Home" }
