[Home]
"q" = "Quit"
"<C-z>" = "Suspend"
"d" = { "SetMode" = "DownloadClient" }
"<enter>" = "Submit"
"asdf" = "Suspend"
"?" = "WhichKey"

[DownloadClient]
"<esc>" = { "SetMode" = "Home" }
"q" = { "SetMode" = "Home" }
"d" = { "SetMode" = "Home" }
