[Home]
"q" = "Quit"
"<C-z>" = "Suspend"
"d" = { "SetMode" = "DownloadClient" }
"<enter>" = "Submit"

[DownloadClient]
"<esc>" = { "SetMode" = "Home" }
"q" = { "SetMode" = "Home" }
"d" = { "SetMode" = "Home" }
