use serde::Deserialize;
use strum::Display;

use crate::app::Mode;

/// Actions generated by the app
#[derive(Display, Debug, Clone, PartialEq, Eq)]
pub enum AppAction {
    Tick,
    Render,
    Resize(u16, u16),
    // Suspend, // TODO: Maybe keep, maybe replace with UserAction::Suspend
    Resume,
    // Quit, // TODO: Maybe keep, maybe replace with UserAction::Quit
    ClearScreen,
    Error(String),
    UserAction(UserAction),
}

/// Actions generated by the user
///
/// In the user keybindings config file, they may be stored as:
/// ```toml
/// "<key>" = "UnitAction"
/// # or
/// "<key>" = { "OneArgAction" = "SingleArg" }
/// # or
/// "<key>" = { "ManyArgAction" = ["Many", "Args"] }
/// ```
///
#[derive(Deserialize, Display, Debug, Clone, PartialEq, Eq)]
pub enum UserAction {
    Quit,
    Suspend,
    Up,
    Down,
    InsertLeft,
    InsertRight,
    InsertNextWord,
    InsertPrevWord,
    Submit,
    SetMode(Mode),
}
