use enum_assoc::Assoc;
use serde::Deserialize;
use strum::Display;
use tui_input::InputRequest;

use crate::{
    app::Mode,
    result::Results,
    sources::{SourceError, query::sort::SortDirection},
};

/// Actions generated by the app
#[derive(Display, Debug, Clone, PartialEq, Eq)]
pub enum AppAction {
    Tick,
    Render,
    Resize(u16, u16),
    Resume,
    ClearScreen,
    Error(String),
    Warning(String),
    Info(String),
    Task(TaskAction),
    Search,
    SetSearch(String),
    SetFilter(usize),
    SetSort(usize, SortDirection),
    UserAction(UserAction),
    Click(u16, u16),
    ClickRelease(u16, u16),
    // TODO: Mouse actions, which are able to make use of cursor position
}

/// Actions generated by the user
///
/// In the user keybindings config file, they may be stored as:
/// ```toml
/// "<key>" = "UnitAction"
/// # or
/// "<key>" = { "OneArgAction" = "SingleArg" }
/// # or
/// "<key>" = { "ManyArgAction" = ["Many", "Args"] }
/// ```
#[derive(Assoc, Deserialize, Display, Debug, Clone, PartialEq, Eq)]
#[func(pub fn name(&self) -> String { self.to_string() })]
pub enum UserAction {
    Quit,
    Suspend,
    Up,
    Down,
    Left,
    Right,
    Top,
    Bottom,
    Submit,
    #[assoc(name = format!("{self}({_0})"))]
    SetMode(Mode),
    WhichKey,
    #[assoc(name = format!("{self}({_0})"))]
    NotifyInfo(String),
    #[assoc(name = format!("{self}({_0})"))]
    NotifyError(String),
    #[assoc(name = format!("{self}({_0})"))]
    NotifyWarning(String),
    ClearNotifications,
    ToggleDebug,
    #[serde(untagged)]
    Insert(InputRequest),
}

/// Actions generated by tasks
///
/// General interface for capturing results across threads
#[derive(Display, Debug, Clone, PartialEq, Eq)]
pub enum TaskAction {
    SourceResults(Result<Option<Results>, SourceError>),
}
