use serde::Deserialize;
use strum::Display;

use crate::app::Mode;

// Actions generated by the app
#[derive(Display, Debug, Clone, PartialEq, Eq)]
pub enum AppAction {
    Tick,
    Render,
    Resize(u16, u16),
    // Suspend, // TODO: Maybe keep, maybe replace with UserAction::Suspend
    Resume,
    // Quit, // TODO: Maybe keep, maybe replace with UserAction::Quit
    ClearScreen,
    Error(String),
    UserAction(UserAction),
}

// Actions generated by the user
#[derive(Deserialize, Display, Debug, Clone, PartialEq, Eq)]
pub enum UserAction {
    Suspend,
    Quit,
    Up,
    Down,
    InsertMoveLeft,
    InsertMoveRight,
    InsertNextWord,
    InsertPrevWord,
    SetMode(Mode),
}
