name: "Test build nix"

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix-path: nixpkgs=channel:nixos-unstable
      - run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - run: nix-build
